# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'teste-mobile' do
  # Pods for teste-mobile
  pod 'Alamofire', '~> 4.4'
end
