# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'teste-mobile' do
  # Pods for teste-mobile
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'PKHUD', '~> 4.0'
  pod 'Kingfisher', '~> 3.0'
end
